spring:
  datasource:
    url: jdbc:postgresql://empawsdb3.cwwffjgbuljv.ap-south-1.rds.amazonaws.com:5432/empawsdb3?sslmode=require
    driverClassName: org.postgresql.Driver
    username: postgres
    password: rootadmin
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    defer-datasource-initialization: true
    show_sql: true
    hibernate:
      ddl-auto: update