spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    defer-datasource-initialization: true
    show_sql: true
    hibernate:
      ddl-auto: update

app:
  emp_career_service_url: ${APP_CAREER_SERVICE_URL}

  /empservice/dev/DB_HOST
  
  /empservice/dev/DB_HOST empawsdb3.cwwffjgbuljv.ap-south-1.rds.amazonaws.com
  /empservice/dev/DB_PORT 5432
  /empservice/dev/DB_NAME empawsdb3
  /empservice/dev/DB_USERNAME postgres
  /empservice/dev/DB_PASSWORD rootadmin
  /empservice/dev/APP_CAREER_SERVICE_URL http://careerservice:8051/api/career
